### Create
POST http://localhost/api/users/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@mail.de",
    "username": "john",
    "password": "123456"
}

### Authentification
POST http://localhost/api/users/authenticate
Content-Type: application/json

{
    "username": "john",
    "password": "123456"
}

### Authentification; Fail
POST http://localhost/api/users/authenticate
Content-Type: application/json

{
    "username": "john",
    "password": "123456"
}

### Profile
GET http://localhost/api/users/profile
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYzI0NTcyYTI2YzE2MzI3YzY0ZmE1NiIsIm5hbWUiOiJKb2huIERvZSIsInVzZXJuYW1lIjoiam9obiIsImVtYWlsIjoiam9obkBtYWlsLmRlIiwiaWF0IjoxNjA2NTcwNTg0LCJleHAiOjE2MDcxNzUzODR9.FdsyuW5ngXx2c9TVrhx8Hr-h1npknPw1dkGM4t3ostQ

### Profile; Fail
GET http://localhost/api/users/profile